name: .NET

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64
    - name: Build
      run: |
        cd Chrysalis-Main
        dotnet publish --no-restore -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: Chrysalis-Windows
        path: Chrysalis-Main/bin/Release/net8.0/win-x64/publish/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64
    - name: Build
      run: | 
        cd Chrysalis-Main
        dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: Chrysalis-Linux
        path: Chrysalis-Main/bin/Release/net8.0/linux-x64/publish/

  build-macos:
    runs-on: macos-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-x64
    - name: Build
      run: |
        cd Chrysalis-Main
        dotnet publish --no-restore -r osx-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
        mkdir out
        python3 make_app.py Chrysalis.app Chrysalis-Main/bin/Release/net8.0/osx-x64/publish
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: Chrysalis-MacOS
        path: out/mac.zip

  release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with: 
          path: ./artifacts

      - name: Zip
        run: |
            zip -jr windows.zip ./artifacts/Chrysalis-Windows/*

            chmod +x ./artifacts/Chrysalis-Linux/Chrysalis
            zip -jr linux.zip ./artifacts/Chrysalis-Linux/*

      - name: Create release if a new tag is pushed
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.head_commit.message }}
          files: |
            ./windows.zip
            ./artifacts/Chrysalis-MacOS/mac.zip
            ./linux.zip
